development:
  adapter: mysql2
  encoding: utf8
  database: events
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: events_test
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: events_production
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
